### ISSUE TITLE
shell run ignores clear buffer character sequences sent by programs

### ISSUE THREAD

**Issue by mattfennerjesi** [axrs/dart_chassis_forge#10]
Some more fancy programs will send character sequences to clear the output buffer. For example unit test programs which watch for file changes and re-run.

Specifically I am interested in [CSI sequences](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences).

I think the most common code is:
`\033[H\033[J`
where:
- \033[H moves the cursor to the top left corner of the screen
- \033[J clears the part of the screen from the cursor to the end of the screen
When used in combination, it results in the screen getting cleared with cursor positioned at the beginning of the screen.

**Comment by mattfennerjesi** [comment]
more details https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797

**Comment by MattFenner** [comment]
turns out ANSI clear codes aren't supported in the version of Powershell which ships with windows. Using Powershell 7.2 or later it works.

Not a problem with Chassis Forge. closing

**Comment by axrs** [comment]
Thanks. I'll close the issue :)
