### ISSUE TITLE
Parameters don't allow spaces

### ISSUE THREAD

**Issue by danielithomas** [axrs/dart_chassis_forge#4]
I had a little program that would do `./jpro.sh query --jql "user=myname and status!=done"` but when the program ran, the parameter (string in quotes) is not passed in fully - everything after the first space is omitted.

**Comment by axrs** [comment]
Indeed.  That should be possible as the quotes should be interpreted as a single value. Definitely something to dive into.

**Comment by danielithomas** [comment]
Update 

1. Did a test with `smart_args` and confirmed it can work with arguments that contain spaces. 
2. Discovered that running the main.dart directly (e.g. in `forge` directory, `dart run main.dart query --jql "user=myname and status!=done"`) works so I suspect it's in the script magic where shenanigans are going on.

**Comment by axrs** [comment]
This should now be fixed in https://github.com/axrs/dart_chassis_forge/commit/b68d603861696d630e43875b7a81005ce1693515

The issue was a result of not quoting the bash argument array, causing the spaced arguments to be incorrectly spread.
